apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  replicas: 4
  # .spec.selector is a required field that specifies a label selector for the Pods targeted by this Deployment.
  selector:
    matchLabels:
      name: api
      env: prod
  template:
    # .spec.selector must match .spec.template.metadata.labels, or it will be rejected by the API.
    metadata:
      labels:
        name: api
        env: prod
    spec:
      containers:
        - name: api
          image: afreydev/companies-backend:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
          command: 
          - bash
          - run.sh
          env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: companies
          - name: MYSQL_DATABASE
            value: companies
          - name: MYSQL_PASSWORD
            value: password