apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  restartPolicy: OnFailure
  containers:
  - image: ubuntu
    command:
    - "sleep"
    - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
