apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: companies
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: k8s
    repoURL: "https://github.com/afreydev/argocd-lab.git"
    targetRevision: main
